spring :
  jpa :
    hibernate :
      ddl-auto : create
    properties :
      hibernate :
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql : true
  session:
    store-type: jdbc

logging:
  level:
    org.hiberbate.SQL: debug
    org.hibernate.type: trace